// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9XikW5_8igpuWJoLjdeGNoF_KSLjulf0',
    appId: '1:22127177105:web:b1463b204157cab30cfe30',
    messagingSenderId: '22127177105',
    projectId: 'quadrofb',
    authDomain: 'quadrofb.firebaseapp.com',
    storageBucket: 'quadrofb.appspot.com',
    measurementId: 'G-0TBGEFTFJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqPhubScZ5t8wecRtj6dRc4ygnARNIec',
    appId: '1:22127177105:android:2c53b9b975dd56870cfe30',
    messagingSenderId: '22127177105',
    projectId: 'quadrofb',
    storageBucket: 'quadrofb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClqb-fSgaDbrED-nghO74_tEwaZcBWPFI',
    appId: '1:22127177105:ios:148b66ba23b5b78f0cfe30',
    messagingSenderId: '22127177105',
    projectId: 'quadrofb',
    storageBucket: 'quadrofb.appspot.com',
    iosClientId: '22127177105-dtfee9pon957dnkb8lrmgiq2ti8ijt55.apps.googleusercontent.com',
    iosBundleId: 'com.example.quadro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClqb-fSgaDbrED-nghO74_tEwaZcBWPFI',
    appId: '1:22127177105:ios:a7a975feec0b612d0cfe30',
    messagingSenderId: '22127177105',
    projectId: 'quadrofb',
    storageBucket: 'quadrofb.appspot.com',
    iosClientId: '22127177105-2iv2dlr3l35us9oef5g8287glkburbt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quadro.RunnerTests',
  );
}
